---
- hosts: web 
  tasks: 
  - name: Update all packages to the latest version
    apt:
        upgrade: dist
  - name: Install the package "git"
    apt:
        name: git
  - name: Install the package "maven"
    apt:
        name: maven
  - name: Add openjdk-r stable repository from PPA and install its signing key
    apt_repository:
        repo: ppa:openjdk-r/ppa
  - name: Update all packages to the latest version
    apt:
        upgrade: dist
  - name: Install the package "openjdk-8-jdk"
    apt:
        name: openjdk-8-jdk
  - name: Git checkout spring-boot-postgress-example from github
    git:
        repo: https://github.com/springframeworkguru/spring-boot-postgress-example
        dest: /vagrant/spring-boot-postgress-example/
        force: yes
  - name: Copy file application.properties with owner and permissions
    copy:
        src: /vagrant/application.properties
        dest: /vagrant/spring-boot-postgress-example/src/main/resources
        owner: root
        group: root
        mode: '0644'
  - name: Install the package "systemd"
    apt:
        name: systemd
  - name: Copy file web.service with owner and permissions
    copy:
        src: /vagrant/web.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: '664'
  - name: Copy file web.sh with owner and permissions
    copy:
        src: /vagrant/web.sh
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '774'
  - name: Force systemd to reread configs
    systemd:
        daemon_reload: yes
  - name: Make sure a service is running
    systemd:
        state: started
        enabled: yes
        name: web